[package]
name = "DIDShield"
version = "0.1.0"
edition = "2018"

[dependencies]
curve25519-dalek = "4.1"
rand = "0.8"
sha2 = "0.10"
lazy_static = "1.4"

[dev-dependencies]
criterion = "0.4"
hex = "0.4"
vrf = { path = "vrf-rs" }

[[bench]]
name = "vrf"
harness = false

