[package]
name = "layer1"
version = "0.1.0"
edition = "2018"

[dependencies]
did-key = { path = "../did-key.rs" }
serde_json = "1"
ethers = { version = "2", features = ["abigen"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
